# Generated by Django 4.0.4 on 2022-06-16 22:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024)),
                ('doi', models.CharField(default='', max_length=1024)),
                ('abstract', models.TextField(default='')),
                ('full_text', models.TextField(default='')),
                ('publication', models.DateField(default=datetime.date(1900, 1, 1))),
                ('url_file', models.URLField(max_length=4096, null=True)),
                ('is_file_get', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=256)),
                ('year_begin', models.DateField(default=datetime.date(1900, 1, 1))),
                ('year_end', models.DateField(default=datetime.date(1900, 1, 1))),
                ('step', models.CharField(default='article', max_length=256)),
                ('is_finish', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('error', models.CharField(default='', max_length=256)),
                ('max_article', models.IntegerField(default=0)),
                ('best_dbcv', models.FloatField(default=0.0)),
                ('process_time', models.IntegerField(default=0)),
                ('current_article_db', models.CharField(default='', max_length=128)),
                ('begining_date', models.DateField(null=True)),
                ('number_neighbour', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadDaemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_running', models.BooleanField(default=False)),
                ('check_still_running', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TableChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_display', models.BooleanField(default=True)),
                ('is_initial', models.BooleanField(default=True)),
                ('is_check', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.article')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Research_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.article')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='articles',
            field=models.ManyToManyField(through='DataBase.Research_Article', to='DataBase.article'),
        ),
        migrations.AddField(
            model_name='research',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=8196)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.article')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.author')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(through='DataBase.Article_Author', to='DataBase.author'),
        ),
    ]
