# Generated by Django 4.0.4 on 2022-04-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablechoice',
            name='is_initial',
            field=models.BooleanField(default=True),
        ),
    ]
