# Generated by Django 3.2 on 2022-04-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_article_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pmcid',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
