# Generated by Django 4.0.4 on 2022-05-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_tablechoice_is_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_temporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_article', models.CharField(max_length=256)),
                ('title', models.CharField(default='', max_length=1024)),
                ('date', models.CharField(default='', max_length=256)),
                ('DOI', models.CharField(default='', max_length=256)),
                ('URL', models.CharField(default='', max_length=1024)),
                ('authors', models.CharField(default='', max_length=1024)),
                ('abstract', models.CharField(default='', max_length=4096)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
    ]
