# Generated by Django 4.0.4 on 2022-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_alter_article_doi_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='topic',
            field=models.CharField(max_length=8196),
        ),
    ]
