# Generated by Django 4.0.4 on 2022-05-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0005_alter_cluster_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research',
            name='max_article',
            field=models.IntegerField(default=0),
        ),
    ]
