# Generated by Django 4.0.4 on 2022-05-22 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0007_alter_article_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='year_begin',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='research',
            name='year_end',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
