# Generated by Django 4.0.4 on 2022-05-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0008_alter_research_year_begin_alter_research_year_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='best_dbcv',
            field=models.FloatField(default=0.0),
        ),
    ]
