# Generated by Django 4.0.4 on 2022-05-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0010_alter_article_abstract_alter_article_full_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='process_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='research',
            name='step',
            field=models.CharField(default='article', max_length=256),
        ),
    ]
