# Generated by Django 4.0.4 on 2022-05-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0011_research_process_time_alter_research_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='current_article_db',
            field=models.CharField(default='', max_length=128),
        ),
    ]
