# Generated by Django 4.0.4 on 2022-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0012_research_current_article_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_file',
            field=models.URLField(max_length=4096, null=True),
        ),
    ]
