# Generated by Django 4.0.4 on 2022-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0013_alter_article_url_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablechoice',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='article_temporary',
        ),
    ]
