# Generated by Django 4.0.4 on 2022-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0015_threaddaemon_remove_article_pmcid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='number_neighbour',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='Preproc',
        ),
    ]
