# Generated by Django 4.0.4 on 2022-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preprocess_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_article', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
