# Generated by Django 4.0.4 on 2022-06-17 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preprocess_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_article', models.IntegerField()),
                ('text', models.TextField()),
                ('research', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
        migrations.CreateModel(
            name='Number_trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
        migrations.CreateModel(
            name='Number_preprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.TextField()),
                ('type', models.TextField()),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
    ]
