# Generated by Django 4.0.4 on 2022-08-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_step',
            name='research',
        ),
        migrations.DeleteModel(
            name='Article_Job',
        ),
        migrations.DeleteModel(
            name='Article_Step',
        ),
    ]
