# Generated by Django 4.0.4 on 2022-05-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0004_alter_article_doi_alter_article_title'),
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='step_processus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=128)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
    ]
