# Generated by Django 4.0.4 on 2022-05-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0006_research_is_running_research_max_article'),
        ('BackEnd', '0004_pid_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trials', models.IntegerField(default=0)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.research')),
            ],
        ),
    ]
