# Generated by Django 4.0.4 on 2022-05-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_remove_number_trial_trials_number_preprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step_processus',
            name='research',
        ),
        migrations.DeleteModel(
            name='PID_Research',
        ),
        migrations.DeleteModel(
            name='step_processus',
        ),
    ]
