# Generated by Django 3.2 on 2022-04-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI_Front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article_author',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article_author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='article',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='research',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='research',
        ),
        migrations.RemoveField(
            model_name='preproc',
            name='article',
        ),
        migrations.RemoveField(
            model_name='preproc',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='preproc',
            name='research',
        ),
        migrations.RemoveField(
            model_name='request',
            name='arguments',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request_argument',
            name='argument',
        ),
        migrations.RemoveField(
            model_name='request_argument',
            name='request',
        ),
        migrations.RemoveField(
            model_name='research',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='research',
            name='request',
        ),
        migrations.RemoveField(
            model_name='research_article',
            name='article',
        ),
        migrations.RemoveField(
            model_name='research_article',
            name='research',
        ),
        migrations.DeleteModel(
            name='Argument',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Article_Author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Preproc',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Request_Argument',
        ),
        migrations.DeleteModel(
            name='Research',
        ),
        migrations.DeleteModel(
            name='Research_Article',
        ),
    ]
